name: Website Monitor

on:
  schedule:
    - cron: "*/3 * * * *" # every 10 minutes
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_MT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_BOT_MT_UPTIME }}
        run: |
          chmod +x UpTime.sh
          ./UpTime.sh
